---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: munu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
mtcars2 <- mtcars[, c("mpg", "cyl", "wt")]

library(tidyverse)
library(flexdashboard)
library(maps)
library(leaflet)
library(sf)
library(plotly)
library(mapview)
library(shiny)

theme_set(theme_classic())
getwd()


all.sites.gwl <- read.csv("../Processed/gwl.sites.joined.csv")
all.sites.gwl <- all.sites.gwl %>% dplyr::select(-X)
all.sites.gwl$Date <- as.Date(all.sites.gwl$Date)

all.sites.gwl.static <- all.sites.gwl %>%
  dplyr::group_by(AgencyCd, SiteNo, DecLongVa, DecLatVa) %>%
  dplyr::summarise(
            firstMeas = min(Date),
            lastMeas = max(Date), 
            Count = length(SiteNo),
            WellDepth = median(WellDepth))

```


Dashboard
=======================================================================
```{r}
# Reactive that returns the whole dataset if there is no brush
selectedData <- reactive({
  data <- brushedPoints(all.sites.gwl.static, input$plot1_brush)
  if (nrow(data) == 0)
    data <- all.sites.gwl.static
  data
})
```

Row {data-height=650}
-----------------------------------------------------------------------

### Miles Per Gallon vs. Weight 

```{r}
plotOutput("plot1", brush = brushOpts(id = "plot1_brush"))
output$plot1 <- renderPlot({
  ggplot(selectedData(), aes(x=DecLongVa, y=DecLatVa, color = WellDepth)) +
  geom_point()
})
```

Row {data-height=350}
-----------------------------------------------------------------------

### Miles Per Gallon and Cylinders {data-width=400}

```{r}
renderPlot({
  ggplot(selectedData(), aes(WellDepth, Depth.to.Water.Below.Land.Surface.in.ft.)) + 
    geom_point() +
    geom_line()
})

```



### Car Details

```{r}
renderTable({
  selectedData()
})
```