---
title: "New Mexico Groundwater"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: united
editor_options: 
  chunk_output_type: console
runtime: shiny
---

```{r setup, include=FALSE}
pacman::p_load(tidyverse, flexdashboard,maps,leaflet,sf,plotly,shiny,viridis,shinyWidgets,scales)
#library(tidyverse)
#library(flexdashboard)
#library(maps)
#library(leaflet)
#library(sf)
#library(plotly)
#library(mapview)
#library(shiny)
#library(viridis)
#library(shinyWidgets) 
#library(scales)
#devtools::install_github("dreamRs/shinyWidgets") 
#install.packages("shinyWidgets")



theme_set(theme_classic())
getwd()

#static df with count and date measurements
sites.summary.static <- readRDS("../Processed/sites.summary.static.rds")
sites.summary.static$firstMeas <- as.Date(sites.summary.static$firstMeas)
sites.summary.static$lastMeas <- as.Date(sites.summary.static$lastMeas)
sites.summary.static$SiteType <- as.factor(sites.summary.static$SiteType)
sites.summary.static$AgencyCd <- as.factor(sites.summary.static$AgencyCd)


table(sites.summary.static$AgencyCd) #mostly USGS wells, but some are NMBGMR
str(sites.summary.static)
summary(sites.summary.static$WellDepth) #so many NAs for welldepth, none are showing up

countylist <- unique(sites.summary.static$CountyNm)
countylist <- sort(countylist)

#gwl data
gwl.joined.skinny <- readRDS("../Processed/gwl.joined.skinny.rds")
gwl.joined.skinny$Date<-as.Date(gwl.joined.skinny$Date)


```

Dashboard
=======================================================================


Sidebar {.sidebar}
-------------------------------------------
Identify desired attributes to narrow down sites on map

```{r}
#Agency selection
checkboxGroupInput("Agency", label = "Agency",
            choices = c("USGS", "NMBGMR"), 
            selected = c("USGS", "NMBGMR"))

#Number of measurements per well
numericInput("Measurements", "Minimum number of measurements per well", value = 1)

#Well Depth
sliderInput("Depth", "Well Depth (ft)",
            min = 0, max = 7400, value = c(0,1000), step = 10)
#setSliderColor("Purple", 1)

#County drop down
pickerInput(
   inputId = "County",
   label = "County", 
    choices = countylist,
   selected = countylist,
   options = list(
      `actions-box` = TRUE), 
    multiple = TRUE
)
#Date of last measurement
dateInput("Dates", "Has ground water level data as recent as:", 
               min = "1900-05-01",max = Sys.Date(), format = "yyyy-mm-dd" , 
               startview = "month", weekstart = 0, language = "en", 
               value = "1900-05-01",width = NULL, autoclose = TRUE)

```

Row {data-height=750} 
-----------------------------------------------------------------------

### Sites

```{r}

selectedData <- reactive({
  m <- subset(sites.summary.static,
              AgencyCd %in% input$Agency &
              WellDepth >= input$Depth[1] & WellDepth <= input$Depth[2] &
              Count >= input$Measurements &
              lastMeas >= as.Date(input$Dates) &
              CountyNm %in% input$County
       ) 
 
  
})

output$map <- renderLeaflet({

  #palette 
  pal <- colorNumeric(magma(999), NULL, reverse = TRUE, na.color = "green")
  
 selectedData() %>%
 leaflet() %>% 
 addTiles()%>%
 addCircleMarkers(~DecLongVa, ~DecLatVa,
                  stroke = FALSE, 
                  fillOpacity = 0.5,
                  radius=5,
                  fillColor = ~pal(WellDepth),
                  popup = ~as.character(`SiteNo`),
                  layerId = ~SiteNo) %>%
 addLegend(position = 'bottomright', pal = pal, na.label = "NA",
                values = selectedData()$WellDepth, title = 'Well Depth (ft)')
})
leafletOutput('map')
```

Row  
-----------------------------------------------------------------------

### Click on a point to see groundwater levels

```{r}

click_marker <- eventReactive(input$map_marker_click, {
  
  x<-input$map_marker_click
  y<-x$id
  return(y)
})

 plot_data <- reactive({
  
  
 # Fetch data for the clicked tract
  
 return(gwl.joined.skinny[gwl.joined.skinny$SiteNo == click_marker(), ])
  
  
 })
 output$well <- renderPlotly({
   p <- ggplot(plot_data(), aes(x=Date, y = DepthToWater)) +
     geom_point() + geom_line() + scale_y_reverse() +
     labs(y="Depth to Water (ft)")
   ggplotly(p)
   
 })
plotlyOutput('well')

```

### Chart B

```{r}
colname <- colnames(sites.summary.static)
table_data <- reactive({
  
  
 # Fetch data for the clicked tract
  
 return(sites.summary.static[sites.summary.static$SiteNo == click_marker(), ])
 rownames(sites.summary.static) <- colname
  
 })

renderTable({t(table_data())
             })
```


About 
==================================================
To-do:


- create "About" page
- submit skinny joined df with "must haves"

- Do sites with NA welldepth show up on map?

- What happened to NA agency codes?
- add aquifer codes, county fips, state names
- add Agency Name to ABQ
